name: Sync to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  sync-to-azure-blob-storage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Sync to Azure Blob Storage
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          # Authenticate to Azure
          az login --service-principal -u ${{ secrets.servicePrincipalId }} -p ${{ secrets.servicePrincipalKey }} --tenant ${{ secrets.tenantId }}

          # Clone the visionai repository to the agent
          git clone https://github.com/visionify/visionai.git

          # Switch to the main branch
          cd visionai
          git checkout main

          # Sync the scenario.json file to the container
          az storage blob upload --destination-path <destination-path> --source scenario.json --account-name <storage-account-name> --account-key <storage-account-key>

      env:
        servicePrincipalId: ${{ secrets.servicePrincipalId }}
        servicePrincipalKey: ${{ secrets.servicePrincipalKey }}
        tenantId: ${{ secrets.tenantId }}
