name: Transfer and Sync to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  transfer-to-azure-blob-storage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transfer to Azure Blob Storage
        uses: Azure/blobxfer@1.5.5
        with:
          storage_account: aksummasa
          storage_account_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          container_name: container
          local_path: ./scenarios.json
          blob_path: /container/myblob.json

  sync-to-azure-blob-storage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Sync to Azure Blob Storage
        env:
          servicePrincipalId: ${{ secrets.servicePrincipalId }}
          servicePrincipalKey: ${{ secrets.servicePrincipalKey }}
          tenantId: ${{ secrets.tenantId }}
        run: |
          az login --service-principal -u $servicePrincipalId -p $servicePrincipalKey --tenant $tenantId
          git clone https://github.com/visionify/visionai.git
          cd visionai
          git checkout main
          az storage blob upload --destination-path /container/myblob.json --source ./scenarios.json --account-name aksummasa --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
